### ISSUE TITLE
Module is always in start mode

### ISSUE THREAD

**Issue by relativy** [p1rse/robot-sumo-start-module#2] opened 2019-10-28 08:50 UTC
Hi guys, 
I have problem with 3 modules i have put in 3 my sumo standard robots. 
They are not responding to any comands, and stay in start mode all the time. 
One module suffer a damage to IR recevier during the competition. I have replace it. 
Other to, did not suffer any physical damage, just suddenly stopped working. 
Did anyone have any idea, what can be wrong, and how to fix it?

**Comment by p1rse** [comment] 2019-10-28 09:02
Hi Relativy.
The module will retain the last state so you have to press stop (light will start to blink) then reset your robot and it will be back to initial state. To help you further please answer the following:
What type of remote are you testing with?
Are the module put in home mode or not?
Best Regards

**Comment by relativy** [comment] 2019-10-28 09:23
HI, i am testing with Sumo Remote app from my phone. I have check all 31 channels to stop the module. It did not worked. Is another way to reset the module?

**Comment by p1rse** [comment] 2019-10-28 09:31
You should be able to send the programming signal, this should be received in the started mode.

**Comment by p1rse** [comment] 2019-10-28 09:33
As you can see here: https://p1r.se/startmodule/implement-yourself/modes-of-operation/
The comment for (4) is just to handle this case.

**Comment by relativy** [comment] 2019-10-28 09:49
The programing signal also did not work, and it looks like there is no way to reset the modules. 
It is also possible that IR recivers are damaged, but I have no way to chceck that out, and it seems unlikely that 3 of them would get damaged.

**Comment by p1rse** [comment] 2019-10-28 09:54
hmm ok, It could be the MCU or Reciever that is dead. If it has happened to 3 modules in the same robot it might be the robot that is killing them? There is a diode on the module to protect the MCU however in Standard sumo there can be very high current and disturbances from the powerful motors. Have you had issues with any other Electronics in your robot. Did the startmodules die during a fight or when high currents have been involved?

**Comment by relativy** [comment] 2019-10-28 10:07
The modules were used i 2 diffrent sumo robots, with diffrent controlers. One is AVR other is STM. 
I dont think motors really have anything to do with that. Logic and Power section are separated opticaly and have their own batteries. So only EM Field fluctuation can generate any interference, but even analog section for sensors hardly show any signs of interferece during fights. 

2 modules died during fight. 1 of them was hit by other robot and the IR reciver was cut out (board is fine). The other died also during fight but with no aparent reason. Third module was locked when I arrived at the competition, so I dont really know when it get stuck in start mode.

**Comment by p1rse** [comment] 2019-10-28 10:14
Ok, I understand. Hard to know what the root cause is, normally the modules are robust.
Are you sure your app is sending commands via IR?
Do you have a normal TV remote that uses RC-5 protocol?
If yes you could try to put the modules in "home mode" and see if it works.

**Comment by relativy** [comment] 2019-10-28 10:18
Honestly I can't be sure if App is sending signal, but it worked before, so i do not expect any issues here. 
I need to check my TV, maybe yes. But i still have a quesion. In order to reset the module do I need to send programing signal at the same channel that the module is set? or program it at any channel and it will reset?

**Comment by p1rse** [comment] 2019-10-28 10:20
The programming command does not have to be the same channel. It should reset when it receives the programming signal regardless of channel.

**Comment by relativy** [comment] 2019-10-28 10:38
I could not find RC5 TV pilot, but i found another module, so my phone working fine. 
I guess the problem is the IR reciver. I will order new ones, replace in all modules and see if it will work, 
becouse nothing elese came to my mind, ant they were to exposed during competition.

**Comment by p1rse** [comment] 2019-10-28 13:57
Ok, let us know if you find the root cause for your issue.

**Comment by relativy** [comment] 2019-11-15 17:29
The spare IR recivers just arrived. I have swaped them, and all my modules working fine now.

**Comment by p1rse** [comment] 2019-11-27 17:34
Good to know, I will close this issue but keep an eye and ear open if we get similar report.
If you find out the root cause please let us know.

**Closed as completed by p1rse** 2019-11-27 17:34 UTC
